# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jchapman <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/16 13:21:37 by jchapman          #+#    #+#              #
#    Updated: 2023/02/16 17:31:02 by jchapman         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

gnlmake: gnltest.c get_next_line.c get_next_line_utils.c
	rm -fr a.out a.out.dYSM
	gcc -Wall -Werror -Wextra -g gnltest.c
